
CREATE DATABASE DOTNET;


 CREATE TABLE HR
 (
     ID INT PRIMARY KEY AUTO_INCREMENT,
     FULLNAME VARCHAR(50) NOT NULL,

     CITY VARCHAR(50) NOT NULL,
     SALARY FLOAT ,
     EMAIL VARCHAR(70) NOT NULL,
     DEPTNO INT NOT NULL



 );




   INSERT INTO HR VALUES (DEFAULT,"PRATIK","SOLAPUR",2500,"PRATIK@GMAIL.COM",10);
   INSERT INTO HR VALUES (DEFAULT,"RAHUL","PUNE",9504,"RAHULHUNARE@GMAIL.COM",20);
   INSERT INTO HR VALUES (DEFAULT,"UDDESH","KOHLAPUR",2500,"UDDDESH@GMAIL.COM",30);
   INSERT INTO HR VALUES (DEFAULT,"OMKAR","KARAD",1500,"TOBS@GMAIL.COM",10);
   INSERT INTO HR VALUES (DEFAULT,"RUPESH","MUMBAI",800,"RUPESS@GMAIL.COM",20);
    INSERT INTO HR VALUES (DEFAULT,"SUMIT","MUMBAI",800,"SUMIT@GMAIL.COM",20);
     INSERT INTO HR VALUES (DEFAULT,"YOGESH","SOLAPUR",900,"YOGESH@GMAIL.COM",20);
